name: Publish Package to GitHub Packages
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          registry-url: "https://npm.pkg.github.com"
          scope: "@opendocs-editor"
      - run: |
          npm install
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
